apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: 3306
  type: ClusterIP