apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
    storage: mysql
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.hostPath }}
  persistentVolumeReclaimPolicy: Retain