apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: 80
    nodePort: {{ .Values.wordpress.service.nodePort }}
  type: {{ .Values.wordpress.service.type }}