# WordPress Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: practice
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort